"""AI Copilot domain schemas."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AIChatRequest(BaseModel):
    message: str = Field(..., min_length=1, description="User prompt or query to AI Copilot")
    context: Optional[Dict[str, Any]] = Field(default=None, description="Optional extra frontend context")


class AIChatResponse(BaseModel):
    response: str = Field(..., description="Context-aware response generated by backend engine")
    intent: Optional[str] = Field(None, description="Identified question intent")
    suggested_actions: List[str] = Field(default_factory=list, description="Follow-up suggested actions")
    context_summary: Optional[Dict[str, Any]] = Field(default=None, description="Summary of real telemetry consulted")
